Sub-folders containing model-specific information
fathomnet/models pull request #4
Opened 2023-05-31 15:51 UTC by Jordan-Pierce

Per the [discussion](https://github.com/fathomnet/models/issues/3), this PR contains the following:

**Updated Main readme** 
- Added the link to the publication,
- Added two additional rows for projects that use FathomNet data

**Sub-folders for each model** 
- Each model has it's own sub-folder in the root of the repo with representative name
- Sub-folders are relatively consistent in structure
- Sub-folders contains folders for scripts, notebooks, resources, figures, and a folder containing the original repo project to easily refer back to
- Sub-folder's readme(s) contain basic information, links to project / publication, and status of that model

Links to HuggingSpace demos are currently public, happy to transfer ownership and make a PR within the Fathomnet HuggingFace organization.

Take what you want, gut what you don't 😎

2023-06-01 20:23 UTC, eor314 commented
I think we should merge most of this to a new branch until after we sort out our future model zoo development strategy. We should definitely merge the new model into the table in the README of main.

2023-06-02 18:13 UTC, eor314 commented
@Jordan-Pierce I added you as a contributor to our HuggingFace community. Do you want to try to PR the Spaces you set up into the FathomNet community there? It'd be cool to get a sense of what the process looks like for potential future model sharing in the HF. Thanks!

2023-06-02 23:10 UTC, Jordan-Pierce commented
Hey @eor314, I just transferred the spaces from my account to the FathomNet account. However, I just re-read your last comment about the PR specifically. How do you feel about me creating a Squid detector space under the FathomNet account, and while it's empty, I'll make a fork, add to the space, and then submit a PR?

2023-06-08 17:43 UTC, kevinsbarnard requested changes
Thanks so much for the PR Jordan! I left some minor comments, but overall I like the structure you've created.

A couple overarching thoughts:
- Including assets (images, videos) in the repo adds quite a bit of bloat, especially when they're duplicated across the different model subdirectories.
- Each model directory lends itself to being its own self-contained repo. I'd suggest breaking each model into a separate repo, then adding them to this one as submodules. That way, we can keep the organization of the models separate from the model assets/scripts themselves. As this repo grows, it may become unwieldy to manage all of them under one roof.

2023-06-08 17:43 UTC, kevinsbarnard commented on .idea/.gitignore
We should exclude IDE configuration from being checked in to the repo -- I recommend removing the `.idea` directory and its contents

2023-06-08 17:43 UTC, kevinsbarnard commented on MBARI_Midwater_Object_Detector/Images/crab.png
Duplicated assets here.

2023-06-08 17:43 UTC, kevinsbarnard commented on MBARI_Monterey_Bay_Benthic/Images/crab.png
Ditto

2023-06-08 17:43 UTC, kevinsbarnard commented on UWROV_Deepsea_Detector/Images/crab.png
Ditto

2025-07-14 20:52 UTC, closed without merging